services:
  # Papermake Server - Template registry HTTP API
  papermake-server:
    build:
      context: .
      dockerfile: crates/papermake-server/Dockerfile
    container_name: papermake-server
    ports:
      - "3000:3000"
    environment:
      # Server configuration
      HOST: "0.0.0.0"
      PORT: "3000"

      # S3 Storage configuration (MinIO)
      S3_ENDPOINT_URL: "http://minio:9000"
      S3_REGION: "us-east-1"
      S3_BUCKET: "papermake-templates"
      S3_ACCESS_KEY_ID: "minioadmin"
      S3_SECRET_ACCESS_KEY: "minioadmin"

      # ClickHouse configuration
      CLICKHOUSE_URL: "http://clickhouse:8123"
      CLICKHOUSE_DATABASE: "papermake"
      CLICKHOUSE_USER: "papermake"
      CLICKHOUSE_PASSWORD: "papermake123"

      # Optional: Enable debug logging
      RUST_LOG: "papermake_server=debug,papermake_registry=debug"
    depends_on:
      minio:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - papermake
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 2s
      timeout: 10s
      retries: 3

  # MinIO S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: papermake-minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - papermake
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 10s
      retries: 3

  # ClickHouse for analytics and render history
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: papermake-clickhouse
    ports:
      - "8123:8123" # HTTP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: papermake
      CLICKHOUSE_USER: papermake
      CLICKHOUSE_PASSWORD: papermake123
    restart: unless-stopped
    networks:
      - papermake
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 2s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
  clickhouse_data:

networks:
  papermake:
    driver: bridge
