services:
  # MinIO S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: papermake-minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - papermake
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # ClickHouse for analytics and render history
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: papermake-clickhouse
    ports:
      - "8123:8123" # HTTP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: papermake
      CLICKHOUSE_USER: papermake
      CLICKHOUSE_PASSWORD: papermake123
    restart: unless-stopped
    networks:
      - papermake
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
  clickhouse_data:

networks:
  papermake:
    driver: bridge
